In [2]:
!pip install --upgrade kmodes


In [9]:
X

array([[738.5, b'tech', b'USA'],
       [369.5, b'nrg', b'USA'],
       [368.2, b'tech', b'USA'],
       [346.7, b'tech', b'USA'],
       [343.5, b'fin', b'USA'],
       [282.4, b'fin', b'USA'],
       [282.1, b'tel', b'CN'],
       [279.7, b'cons', b'USA'],
       [257.2, b'cons', b'USA'],
       [205.2, b'tel', b'USA'],
       [192.1, b'tech', b'USA'],
       [195.7, b'nrg', b'NL']], dtype=object)

In [10]:
syms

array(['AAPL', 'XOM', 'GOOGL', 'MSFT', 'BRK-A', 'WFC', 'CHL', 'JNJ',
       'WMT', 'VZ', 'ORCL', 'RDS-A'], dtype='<U5')

In [6]:
import numpy as np
from kmodes.kprototypes import KPrototypes

# stocks with their market caps, sectors and countries
syms = np.genfromtxt('stocks.csv', dtype=str, delimiter=',')[:, 0]
X = np.genfromtxt('stocks.csv', dtype=object, delimiter=',')[:, 1:]
X[:, 0] = X[:, 0].astype(float)

kproto = KPrototypes(n_clusters=4, init='Cao', verbose=2)
clusters = kproto.fit_predict(X, categorical=[1, 2])

# Print cluster centroids of the trained model.
print(kproto.cluster_centroids_)
# Print training statistics
print('cost: --------------\n')
print(kproto.cost_)
print('n_iter_: --------------\n')
print(kproto.n_iter_)

for s, c in zip(syms, clusters):
    print(f"Symbol: {s}, cluster:{c}")

Initialization method and algorithm are deterministic. Setting n_init to 1.
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/100, moves: 1, ncost: 1664.4708549504871
Run: 1, iteration: 2/100, moves: 0, ncost: 1664.4708549504871
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 2, iteration: 1/100, moves: 0, ncost: 11515.512167176443
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 3, iteration: 1/100, moves: 2, ncost: 78210.0928020971
Run: 3, iteration: 2/100, moves: 5, ncost: 7248.327507312487
Run: 3, iteration: 3/100, moves: 3, ncost: 1664.470854950487
Run: 3, iteration: 4/100, moves: 0, ncost: 1664.470854950487
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run:

In [37]:
import pandas as pd
X = pd.DataFrame([['Male', 1,9], ['Female', 3,11], ['Female', 2,10]], columns=['gender','group','age'])
X

gender  group  age
0    Male      1    9
1  Female      3   11
2  Female      2   10

In [71]:
from sklearn.preprocessing import MinMaxScaler
data = pd.DataFrame([[-1, 2], [-0.5, 6], [0, 10], [1, 18]], columns=['age','age2'])
data
scaler = MinMaxScaler()

scaler.fit_transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [40]:
from sklearn.preprocessing import OneHotEncoder
cat_features=['gender','group']
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit_transform(X[cat_features]).toarray()

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [23]:
enc.fit_transform(X).toarray().shape

(3, 5)

In [24]:
enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3])]

In [25]:
enc.get_feature_names_out(['gender', 'group'])

array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'],
      dtype=object)

In [64]:
def test(cat_features):
#    enc = OneHotEncoder(handle_unknown='ignore')
    enc = OneHotEncoder(drop='first')
    X_cat = enc.fit_transform(X[cat_features]).toarray()
    new_cat_features=[]
#    print(enc.get_feature_names_out(['gender', 'group']))
    for c in range(len(cat_features)):
        new_cat_features.extend(list(enc.categories_[c]))
#    print(enc.categories_)
#    print(new_cat_features)
    new_cat_features = enc.get_feature_names_out(cat_features)
    X_cat = pd.DataFrame(X_cat, columns=new_cat_features)#new_cat_features)
    print(X_cat)
    numeric_features=['age']
    return pd.concat([X_cat,X[numeric_features]],axis=1)
                                    
                            
    #X_cat = enc
    return X_cat
test(cat_features)
#pd.DataFrame(enc.fit_transform(X).toarray(), columns=)
#enc.categories_[0]#.tolis()
#list(enc.categories_[0])

   gender_Male  group_2  group_3
0          1.0      0.0      0.0
1          0.0      0.0      1.0
2          0.0      1.0      0.0


gender_Male  group_2  group_3  age
0          1.0      0.0      0.0    9
1          0.0      0.0      1.0   11
2          0.0      1.0      0.0   10

In [26]:
drop_enc = OneHotEncoder(drop='first').fit(X)
drop_enc.categories_
#[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
#drop_enc.transform([['Female', 1], ['Male', 2]]).toarray()


[array(['Female', 'Male'], dtype=object), array([1, 2, 3])]

In [27]:
drop_enc.transform(X).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [28]:
X

gender  group
0    Male      1
1  Female      3
2  Female      2